### ISSUE TITLE
Inactive tabs very hard to read

### ISSUE THREAD

**Issue by winkler1** [georgeOsdDev/react-draggable-tab#1]
Hi-
 This is cool! Have not seen this implemented before. One issue with the demo-- the inactive tabs are super hard to read. This will make for a less compelling screenshot when I add to react.rocks. Could you have the text be lighter and easier to read please? Thanks.

![image](https://cloud.githubusercontent.com/assets/883896/7960026/7505ab78-09cb-11e5-9537-fba1ec15d53f.png)

**Comment by georgeOsdDev** [comment]
@winkler1 
Thanks for nice feedback.
I updated demo and GIF in README.
[![Gyazo](http://i.gyazo.com/faea8029a68a9c1ea9bf4a588e5ac5a6.gif)](http://gyazo.com/faea8029a68a9c1ea9bf4a588e5ac5a6)
