### ISSUE TITLE
Styling props are not working

### ISSUE THREAD

**Issue by riteshbathwal** [georgeOsdDev/react-draggable-tab#120]
Hi , all of my tabs are working, but when I tried to customise it via styling props, it is not getting overridden. Please check my code below:

const tabStyles = {
            tabActive: {
                backgroundImage: 'linear-radient(rgb(97, 54, 255), rgb(81, 36, 237))'
            },
            tabTitle: {
                fontWeight: 'bold !important',
                color: 'red'
            },
            tabBefore: {
                backgroundImage: 'linear-gradient(rgb(97, 54, 255), rgb(81, 36, 237))',
                boxShadow:'rgb(117, 74, 255) 1px 1px 0px inset, rgba(117, 74, 255, 0.1) -4px 0px 4px'
            },
            tabAfter: {
                backgroundImage: 'linear-gradient(rgb(97, 54, 255), rgb(81, 36, 237))',
                boxShadow:'rgb(117, 74, 255) 1px 1px 0px inset, rgba(117, 74, 255, 0.1) -4px 0px 4px'
            }
        };

 <Tabs
        tabAddButton={null}
        tabs={tabs}     
        tabStyles={tabStyles}
        tabsClassNames={
                {tabTitle: Styles.TabTitle, tabActive: Styles.TabActive }
        }
        selectedTab={this.state.selectedTab ? this.state.selectedTab : "0"}                                
        containerStyle={containerStyle}

/>

Neither the tabStyles are working nor the tabClassNames are working. Please advice on priority.

**Comment by georgeOsdDev** [comment]
use `tabStyles ` instead of `tabStyles`
https://github.com/georgeOsdDev/react-draggable-tab#style-all-tabs-will-be-apply-these-styles
