### ISSUE TITLE
Name a tab

### ISSUE THREAD

**Issue by surabhilabs** [georgeOsdDev/react-draggable-tab#15]
A Feature request. Is it possible to add capability to name/rename a tab? may be ondblclick?

**Comment by georgeOsdDev** [comment]
@surabhilabs 
I add `onTabDoubleClicked` handler at #16.
It just notify double clicked tab's key. Input text area needs shown by application side.
I also updated [example](http://georgeosddev.github.io/react-draggable-tab/example/).
P.S Example code is little bit ugly. It must be written on flux architecture.
