### ISSUE TITLE
Warning: Failed propType: Invalid prop `0` supplied to `Tabs`, expected a ReactElement. Check the render method of `App`.

### ISSUE THREAD

**Issue by gbmhunter** [georgeOsdDev/react-draggable-tab#34]
I get the warning:

`Warning: Failed propType: Invalid prop `0` supplied to `Tabs`, expected a ReactElement. Check the render method of `App`.`

and then the error:

`Uncaught Error: Invariant Violation: There should be unique key in each Tab`

when trying to run this on Electron (Chrome-based desktop app).

I am using gulp-babel to compile the files in components before importing them into my React views.

**Comment by georgeOsdDev** [comment]
They are warning message from React.
https://facebook.github.io/react/docs/reusable-components.html#prop-validation

1st message.
I think you are using `Tabs` component inside your `App`'s `render` method.
And something invalid prop is passed to `Tabs` component.
Below is expected  `propTypes`of `Tabs` component.
https://github.com/georgeOsdDev/react-draggable-tab/blob/master/components/Tabs.js#L469-L512

2nd message.
`Tabs` component expect `tabs` prop as `React.PropTypes.arrayOf(React.PropTypes.element)`.
It is required to use unique `key` if same component are used in array.
http://stackoverflow.com/questions/28329382/understanding-unique-keys-for-array-children-in-react-js

See example,
https://github.com/georgeOsdDev/react-draggable-tab/blob/master/example/app.js#L47-L67

**Comment by gbmhunter** [comment]
The weird thing is I followed that example, in a copy-paste kind of fashion, and that is what gave me these errors. The tabs are saved into `this.state` and then passed to the prop, as per your example.

**Comment by georgeOsdDev** [comment]
Hi @gbmhunter 

Is there any reproduce steps for that warnings?
Or please put your code snippets.

BTW, I deployed develop branch's example on electron.
And it seems work well.
https://github.com/georgeOsdDev/electron-quick-start

**Comment by gbmhunter** [comment]
Maybe I am using a different version of react, or that fact I am pre-compiling with babel (I think you are using a dynamic loader/polyfill?), or because I don't have libraries like lodash installed?

**Comment by gbmhunter** [comment]
Note: I am using React v0.14.0 while this repository uses React v0.13.3, could this be the cause of the problem?

**Comment by gbmhunter** [comment]
I have narrowed it down to React not liking the `tabs` prop passed to the `Tabs` component.

**Comment by georgeOsdDev** [comment]
Hi
I'll try update React.js from 0.13.3 to 0.14.x.
#35

> I think you are using a dynamic loader/polyfill?
I also using browserify & babel.

**Comment by rickyrauch** [comment]
Same error with 0.14.x

**Comment by gbmhunter** [comment]
Interesting, @georgeOsdDev , did you end up testing v0.14.x?

**Comment by georgeOsdDev** [comment]
I'm working it with 
https://github.com/georgeOsdDev/react-draggable-tab/tree/feature/%2335_UpdateDependencies

After fixing up failing tests, I will release new version.

**Comment by georgeOsdDev** [comment]
Hi all,
I released v0.4.0 to NPM, and It support React v0.14.x

**Comment by gbmhunter** [comment]
Champion! Will test soon...

**Comment by rickyrauch** [comment]
@georgeOsdDev thanks man
