### ISSUE TITLE
When tab title is truncated onhover does not show whole title

### ISSUE THREAD

**Issue by d1820** [georgeOsdDev/react-draggable-tab#48]
Seems when lots of tabs are open and the control truncates the tab title, there is no way to see the complete title on hover of the tab.

**Comment by georgeOsdDev** [comment]
@d1820 

Thank you for feedback.
I added title attribute to title element.
Browser will show it with default tooltip like below.
![screen shot 2016-02-02 at 10 34 27 am](https://cloud.githubusercontent.com/assets/1381907/12737269/68edf4aa-c99a-11e5-8125-1a22f20defa5.png)

This change will be included next release.

BTW
You can also use `onTabMouseEnter` and `onTabMouseLeave` event handler to implement your own tooltip. 
https://github.com/georgeOsdDev/react-draggable-tab/tree/develop#events
