### ISSUE TITLE
Unable to add styles or css classes to the tab content div

### ISSUE THREAD

**Issue by d1820** [georgeOsdDev/react-draggable-tab#50]
When adding child elements to a Tab element, there are no available props or styles or classNames which give you the ability to add to how the content div is rendered:
Example
what is output today:
`<div style="width:100%;position:relative;text-align:initial;" data-reactid=".1.0.2.0.1:$tabTemplate#overview"><div data-reactid=".1.0.2.0.1:$tabTemplate#overview.$overview">...</div>`

i have no way reliably to add to the style tag unless i create a css rule to traverse the DOM by x div children.

It would be nice to have a default class or style available on this div container to adjust it. In my case adding a height: 100% to support in components needing a scrollable container that can be dynamically set with css.

Is there any way already available that i am missing?

**Comment by georgeOsdDev** [comment]
@d1820 

This lib does not care the content of `Tab`.
You can adjust content by yourself like below.

```javascript
const MYSTYLE = {
  tab1: {backgroundColor: 'red', height:'100%'},
};

class YourApp extends React.Component {
  constructor(props) {
    super(props);
  }
  render(){
    return (
        <Tabs
          tabs={[
             (<Tab key='tab1'><div ref='myTab1' style={MYSTYLE.tab1}><p>Hello</p></div></Tab>),
             (<Tab key='tab2'><YourComponentWithYourStyle /></Tab>)
          ]}
        />
    );
  }
}
```

**Comment by d1820** [comment]
That would put a custom style on the content itself which works great. I need control of what styles are output from the` <Tab>` itself, those are preset. See output 
`<div style="width:100%;position:relative;text-align:initial;" data-reactid=".1.0.2.0.1:$tabTemplate#overview"><div data-reactid=".1.0.2.0.1:$tabTemplate#overview.$overview">...</div>`

**Comment by georgeOsdDev** [comment]
I understand what you mean.
Added new prop `containerStyle` to `Tab` component.
I will release 0.4.3 soon.

**Comment by georgeOsdDev** [comment]
V0.4.3 is released to NPM.
https://github.com/georgeOsdDev/react-draggable-tab/releases/tag/v0.4.3
