### ISSUE TITLE
Context menu on right click

### ISSUE THREAD

**Issue by musbaig** [georgeOsdDev/react-draggable-tab#53]
Any plans on supporting right click mouse events on a tab? Also, any plans on supporting context menu on right click on a tab? 
Fantastic work thus far btw, a huge thanks!!

**Comment by georgeOsdDev** [comment]
Nice feedback.
I think we can support all events.
https://facebook.github.io/react/docs/events.html#supported-events

Idea:
```
let {
 reservedProps,
 ...others
} = tab.props;

render(){
  return (
   <ul>
     <li style={tabStyle} className={tabClasses}
              onClick={this.handleTabClick.bind(this, tab.key)}
              onMouseDown={this.handleMouseDown.bind(this, tab.key)}
              onMouseEnter={this.handleMouseEnter.bind(this, tab.key)}
              onMouseLeave={this.handleMouseLeave.bind(this, tab.key)}
              ref={tab.key}
              {...others}>
  )
}

```

**Comment by musbaig** [comment]
Awesome!! Thanks for the quick turnaround and in particular this enhancement, cheers!

**Comment by georgeOsdDev** [comment]
V0.5.0 is published to NPM. Please try new version.
Also example is updated http://georgeosddev.github.io/react-draggable-tab/example/.

Thanks.
