### ISSUE TITLE
Confused about CSS support

### ISSUE THREAD

**Issue by davey-h** [georgeOsdDev/react-draggable-tab#56]
I'm a bit lost about CSS support and was wondering if you would help clear that up.

I see that you mention
>tabClassNames: classNames which will be added to rendered elements.

which makes me think that react `classNames` are supported but I don't see any css class references on any of the components and figured I was misunderstanding and wanted to double check.

Thanks

**Comment by georgeOsdDev** [comment]
`tabsClassNames` it self is not react `classNames`, but key-value object of `classNames`.
```
Tabs.propTypes = {
  tabsClassNames: React.PropTypes.shape({
    tabBar: React.PropTypes.string,
    tabBarAfter: React.PropTypes.string,
    tab: React.PropTypes.string,
    tabBefore: React.PropTypes.string,
    tabAfter: React.PropTypes.string,
    tabBeforeTitle: React.PropTypes.string,
    tabTitle: React.PropTypes.string,
    tabAfterTitle: React.PropTypes.string,
    tabCloseIcon: React.PropTypes.string,
    tabActive: React.PropTypes.string,
    tabHover:  React.PropTypes.string
  })
```

You can use it like below
https://github.com/georgeOsdDev/react-draggable-tab/blob/master/test/components/Tabs_spec.js#L228

**Comment by davey-h** [comment]
ok, yeah that makes sense. Thanks
