### ISSUE TITLE
Allow overriding TabStyles.wrapper using props

### ISSUE THREAD

**Issue by uriklar** [georgeOsdDev/react-draggable-tab#59]
Hi, 
Sorry for all the issues.. Promise I'll work on a PR or two once I have some time. 
In the meantime, it would be great the library would expose all style props so they can be overridden.
In my case I need to override the TabStyles.wrapper object.

Another good alternative would be to add a class to the wrapper so it could be overriden in CSS
Thanks, 
Uri

**Comment by georgeOsdDev** [comment]
@uriklar 

Hi Uri,
I added `tabsClassNames.tabWrapper ` and `tabsStyles.tabWrapper`.
I will release new version soon.

**Comment by georgeOsdDev** [comment]
v0.5.1
https://www.npmjs.com/package/react-draggable-tab
