### ISSUE TITLE
React v15 support

### ISSUE THREAD

**Issue by musbaig** [georgeOsdDev/react-draggable-tab#63]

**Comment by georgeOsdDev** [comment]
@musbaig 
Released v0.6.0 to the NPM!
https://www.npmjs.com/package/react-draggable-tab
https://github.com/georgeOsdDev/react-draggable-tab/releases/tag/v0.6.0

**Comment by musbaig** [comment]
Awesome, thank you so much!! Thanks again for all the great work with this library!
