### ISSUE TITLE
Improve tab rendering perfomance

### ISSUE THREAD

**Issue by HaNdTriX** [georgeOsdDev/react-draggable-tab#68]
react-draggable-tab [hides a tab](https://github.com/georgeOsdDev/react-draggable-tab/blob/master/src/components/TabContainer.js#L4-L14) by setting its `height: 0`.
This means, that the contents of each tab need to be resized every time the tab is selected.
This may cause the view engine to render the selected tab very slowly. 

### Solution 1: 

Switch to absolute hiding 

    // Hide
    left: -9999999px;

    // Show
    left: 0;

### Solution 2: 

Let the user configure the [hiding styles](https://github.com/georgeOsdDev/react-draggable-tab/blob/master/src/components/TabContainer.js#L4-L14) via props

**Comment by aleksandrenko** [comment]
Why can't you just use display: none;?

**Comment by georgeOsdDev** [comment]
I added `hiddenConteinerStyle` 5084ea54c713a22bc69e707372ca44a38e2821a8
User now can use any hidden style.

When you use `left: -9999999px` it cause unexpected scrollbar and space when after tab is selected.
Any good idea??

**Comment by georgeOsdDev** [comment]
PS: `display: none;` cause browser re-flow.

http://stackoverflow.com/questions/11757016/performance-differences-between-visibilityhidden-and-displaynone

**Comment by HaNdTriX** [comment]
@georgeOsdDev Awesome! Thanks a lot!

**Comment by georgeOsdDev** [comment]
v0.7.0 is now available on NPM!
https://github.com/georgeOsdDev/react-draggable-tab/releases/tag/v0.7.0
