### ISSUE TITLE
Invariant Violation: addComponentAsRefTo(...): ...

### ISSUE THREAD

**Issue by aleksandrenko** [georgeOsdDev/react-draggable-tab#73]
bundle.js:9824 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Use case in simple react app:

```
..
getInitialState() {
    return {
      tabs:[
        (<Tab key={'tab0'} title={'Tab'}>
          <div>
            <h1>This tab cannot close</h1>
          </div>
        </Tab>)
      ]
    }
  },

  render() {
    return (
        <section>

          <Tabs
            tabs={this.state.tabs}
          />
...
```

**Comment by georgeOsdDev** [comment]
I just published v0.9.0 to NPM.
