### ISSUE TITLE
Cannot read property 'getComputedStyle' of undefined

### ISSUE THREAD

**Issue by uriklar** [georgeOsdDev/react-draggable-tab#75]
Getting this error from react-draggable after upgrading react to version 15.2.1
from https://github.com/mzabriskie/react-draggable/issues/186 I see it can be resolved by using react-draggable version 2.1.2.

**Comment by georgeOsdDev** [comment]
@uriklar 
Thanks.
Can we use react-draggable v2.2.1?

**Comment by uriklar** [comment]
@georgeOsdDev Yes we can! Just tested with v2.2.1 and the error is gone. 
So I guess you can revert my PR...
Thanks!

**Comment by parlop** [comment]
I had the same error then I updated react-draggable to 2.1.2 and everything is fine, thanks.

**Comment by georgeOsdDev** [comment]
Hi all
I have updated react-draggable to v2.2.1, and released react-draggable-tab v0.8.0
https://www.npmjs.com/package/react-draggable-tab

Thanks!
