### ISSUE TITLE
how can I add a confirm dialog to a tab when I want to close it

### ISSUE THREAD

**Issue by parlop** [georgeOsdDev/react-draggable-tab#77]
hello, how can I add a confirm dialog(when YES tab closes and when NO do nothing).
 thanks for sharing this useful react component.

**Comment by georgeOsdDev** [comment]
Hi @parlop 
I have added `shouldTabClose` prop to confirm before close tub.
Please use v0.8.0.
Thanks.

**Comment by parlop** [comment]
@georgeOsdDev just updated to v0.8.0, thanks man.

**Comment by georgeOsdDev** [comment]
@parlop 
Yes, It's expected behavior.
In gh-page example, close from right click mean updating `tabs` prop from `app.js`
See this line.
https://github.com/georgeOsdDev/react-draggable-tab/blob/master/example/app.js#L178

**Comment by parlop** [comment]
Thanks for the clarification, keep up the good work!
