### ISSUE TITLE
Renamable Tabs

### ISSUE THREAD

**Issue by jwesly** [georgeOsdDev/react-draggable-tab#79]
Will there be any support for renamable tabs in the future? Thanks

**Comment by georgeOsdDev** [comment]
Try double click on example.
http://georgeosddev.github.io/react-draggable-tab/example/
https://github.com/georgeOsdDev/react-draggable-tab/blob/master/example/app.js

**Comment by jwesly** [comment]
looks like the double click event that relied upon is deprecated in v0.5.0. Is there a reason not to use the old version or will the functionality be readded at some point?

**Comment by georgeOsdDev** [comment]
onXXX except `onClick`, `onMouseover`, `onMouseLeave` will be passed to `Tab`
https://github.com/georgeOsdDev/react-draggable-tab/blob/master/src/components/Tabs.js#L426-L429

See #53

Thanks
