### ISSUE TITLE
Tab content only renders when tab is clicked

### ISSUE THREAD

**Issue by PeterSchulzNL** [georgeOsdDev/react-draggable-tab#84]
I'm trying to get this component to work in my app, which has a tree with a number of links. The tree and the tabs are two different objects. When I click on a link a tab is added, but I have to click on the tab to render the content of the new tab. What can I do to render automatically? THX

**Comment by georgeOsdDev** [comment]
Can you update `selectedTab` props of `Tabs`?

**Comment by PeterSchulzNL** [comment]
Here is my code:

`       let url = "...some url...";
        const key = 'newTab_' + Date.now();
        let newTab =
            <Tab key={key} title={url}>
              <ExplorerFrameTab url={url} />
            </Tab>;
        let currentTabs = this.state.tabs;
        let newTabs = currentTabs.concat([newTab]);
        this.setState({
            tabs: newTabs,
            selectedTab: key
        });
`

That tab is displayed, but I have to click on the tab to get the ExplorerFrameTab displayed. ExplorerFrameTab  is a react component. I think the selectedTab is updated through setState.

Any ideas...?

**Comment by PeterSchulzNL** [comment]
Solved! ;-) I updated the state (added selectedTab) but forgot to update the property selectedTab in the render function.

```
<Tabs
   ...
   selectedTab={this.state.selectedTab}
   ...
/>
```
