### ISSUE TITLE
'react-tap-event-plugin' errors in Example app

### ISSUE THREAD

**Issue by shanejdonnelly** [georgeOsdDev/react-draggable-tab#88]
When running the app with `npm run start:example` this error happens:

![screen shot 2016-12-22 at 9 56 28 am](https://cloud.githubusercontent.com/assets/1114645/21430074/95fb2794-c82f-11e6-8f2b-ec4d27697868.png)

Fixed by removing react-tap-event. https://github.com/georgeOsdDev/react-draggable-tab/pull/87

By the way - this is a great library! Thanks for creating it.

**Comment by georgeOsdDev** [comment]
#87
